/**
 * 500-entry transition preset catalog.
 *
 * Each preset compiles into a `ClipTransition` whose `type` is `"param"`
 * and whose `params` payload feeds `getTransitionMod()` in
 * `animation.ts`. Because the renderer reads from `params` we don't need
 * a separate string discriminant per variant — adding 500 transitions
 * costs ~one entry per preset, not one switch case per preset.
 *
 * Presets are generated by composing a few "motion families" (slide,
 * push, wipe, zoom, blur, spin, iris, color flash, drop, shake, swirl,
 * reveal) across an axis grid (direction × intensity × color × decoration).
 * Skip rules ensure we only emit visually distinct combinations and the
 * total clears 500 with room to spare.
 */

import type { ParamTransitionParams } from "./types";

export type TransitionPresetCategory =
  | "Slide"
  | "Push"
  | "Wipe"
  | "Zoom"
  | "Blur"
  | "Spin"
  | "Iris"
  | "Color Flash"
  | "Drop & Pop"
  | "Shake & Glitch"
  | "Swirl & Morph"
  | "Cinematic"
  | "Reveal";

export interface TransitionPreset {
  /** Stable id stored as `clip.transitionIn.presetKey`. */
  key: string;
  /** Display name in the picker. */
  label: string;
  /** Visual grouping in the UI. */
  category: TransitionPresetCategory;
  /** Compiled into clip.transitionIn.params. */
  params: ParamTransitionParams;
  /** Suggested duration in seconds. Caller may override. */
  duration?: number;
}

// ── Axis grids reused across multiple families ─────────────────────────────
const DIR8 = [
  { key: "left",  arrow: "←",  dx:  1, dy:  0 },
  { key: "right", arrow: "→",  dx: -1, dy:  0 },
  { key: "up",    arrow: "↑",  dx:  0, dy:  1 },
  { key: "down",  arrow: "↓",  dx:  0, dy: -1 },
  { key: "ul",    arrow: "↖",  dx:  1, dy:  1 },
  { key: "ur",    arrow: "↗",  dx: -1, dy:  1 },
  { key: "dl",    arrow: "↙",  dx:  1, dy: -1 },
  { key: "dr",    arrow: "↘",  dx: -1, dy: -1 },
] as const;

const DIR4 = DIR8.slice(0, 4);

const COLOR_PALETTE: { key: string; label: string; color: string }[] = [
  { key: "white",   label: "White",   color: "#ffffff" },
  { key: "black",   label: "Black",   color: "#000000" },
  { key: "red",     label: "Red",     color: "#ef4444" },
  { key: "rose",    label: "Rose",    color: "#f43f5e" },
  { key: "orange",  label: "Orange",  color: "#fb923c" },
  { key: "amber",   label: "Amber",   color: "#fbbf24" },
  { key: "gold",    label: "Gold",    color: "#facc15" },
  { key: "lime",    label: "Lime",    color: "#a3e635" },
  { key: "emerald", label: "Emerald", color: "#10b981" },
  { key: "teal",    label: "Teal",    color: "#14b8a6" },
  { key: "cyan",    label: "Cyan",    color: "#22d3ee" },
  { key: "sky",     label: "Sky",     color: "#0ea5e9" },
  { key: "blue",    label: "Blue",    color: "#3b82f6" },
  { key: "indigo",  label: "Indigo",  color: "#6366f1" },
  { key: "violet",  label: "Violet",  color: "#8b5cf6" },
  { key: "purple",  label: "Purple",  color: "#a855f7" },
  { key: "fuchsia", label: "Fuchsia", color: "#d946ef" },
  { key: "pink",    label: "Pink",    color: "#ec4899" },
];

const INTENSITY = [
  { key: "soft",    label: "Soft",    mul: 0.6 },
  { key: "normal",  label: "",        mul: 1.0 },
  { key: "strong",  label: "Strong",  mul: 1.4 },
  { key: "extreme", label: "Extreme", mul: 1.8 },
];

function pushPreset(out: TransitionPreset[], p: TransitionPreset): void {
  out.push(p);
}

// ── Family generators ──────────────────────────────────────────────────────

function genSlide(out: TransitionPreset[]) {
  // 8 dirs × 4 intensity × 2 decoration (clean / blur) = 64
  for (const d of DIR8) {
    for (const it of INTENSITY) {
      for (const deco of [
        { key: "clean", label: "",          extra: {} as ParamTransitionParams },
        { key: "blur",  label: "Blur",      extra: { blurPx: 14 } as ParamTransitionParams },
      ]) {
        const labelBits = ["Slide", d.arrow, it.label, deco.label].filter(Boolean).join(" ");
        pushPreset(out, {
          key: `slide-${d.key}-${it.key}-${deco.key}`,
          label: labelBits,
          category: "Slide",
          params: { dx: d.dx * it.mul, dy: d.dy * it.mul, fade: 1, ...deco.extra },
          duration: 0.6,
        });
      }
    }
  }
}

function genPush(out: TransitionPreset[]) {
  // 8 dirs × 4 intensity × 2 decoration (fade / blur) = 64
  for (const d of DIR8) {
    for (const it of INTENSITY) {
      for (const deco of [
        { key: "fade", label: "Fade", extra: { fade: 0.6 } as ParamTransitionParams },
        { key: "blur", label: "Blur", extra: { blurPx: 10, fade: 0.7 } as ParamTransitionParams },
      ]) {
        pushPreset(out, {
          key: `push-${d.key}-${it.key}-${deco.key}`,
          label: ["Push", d.arrow, it.label, deco.label].filter(Boolean).join(" "),
          category: "Push",
          params: { dx: d.dx * it.mul, dy: d.dy * it.mul, ...deco.extra },
          duration: 0.55,
        });
      }
    }
  }
}

function genWipe(out: TransitionPreset[]) {
  // Cardinal wipes: 4 dirs × 4 intensities × 2 decoration (clean / colored) using primary colors = 32
  // Diagonal wipes: 4 dirs × 4 intensities = 16
  // Total: 48
  const colorAccents = [
    { key: "clean", label: "",       extra: {} as ParamTransitionParams },
    { key: "tint",  label: "Tint",   extra: { color: "#ffffff", colorAmp: 0.3 } as ParamTransitionParams },
  ];
  for (const d of DIR4) {
    for (const it of INTENSITY) {
      for (const acc of colorAccents) {
        pushPreset(out, {
          key: `wipe-${d.key}-${it.key}-${acc.key}`,
          label: ["Wipe", d.arrow, it.label, acc.label].filter(Boolean).join(" "),
          category: "Wipe",
          params: {
            wipeLeft:   d.key === "left"  ? 0.5 * it.mul : 0,
            wipeRight:  d.key === "right" ? 0.5 * it.mul : 0,
            wipeTop:    d.key === "up"    ? 0.5 * it.mul : 0,
            wipeBottom: d.key === "down"  ? 0.5 * it.mul : 0,
            ...acc.extra,
          },
          duration: 0.55,
        });
      }
    }
  }
  for (const d of DIR8.slice(4)) { // diagonals
    for (const it of INTENSITY) {
      pushPreset(out, {
        key: `wipe-diag-${d.key}-${it.key}`,
        label: ["Wipe Diag", d.arrow, it.label].filter(Boolean).join(" "),
        category: "Wipe",
        params: {
          wipeLeft:   d.dx > 0 ? 0.5 * it.mul : 0,
          wipeRight:  d.dx < 0 ? 0.5 * it.mul : 0,
          wipeTop:    d.dy > 0 ? 0.5 * it.mul : 0,
          wipeBottom: d.dy < 0 ? 0.5 * it.mul : 0,
        },
        duration: 0.55,
      });
    }
  }
}

function genZoom(out: TransitionPreset[]) {
  // 4 base styles × 4 intensities × 3 decorations = 48
  const styles = [
    { key: "in",      label: "In",      from: 0.4, to: 1.4 },
    { key: "out",     label: "Out",     from: 1.6, to: 0.6 },
    { key: "punch",   label: "Punch",   from: 0.7, to: 1.3 },
    { key: "warp",    label: "Warp",    from: 0.5, to: 1.7 },
  ];
  const decos = [
    { key: "clean", label: "",         extra: {} as ParamTransitionParams },
    { key: "blur",  label: "Blur",     extra: { blurPx: 18 } as ParamTransitionParams },
    { key: "spin",  label: "Spin",     extra: { rotateDeg: 360 } as ParamTransitionParams },
  ];
  for (const s of styles) {
    for (const it of INTENSITY) {
      for (const deco of decos) {
        const scale = it.mul;
        pushPreset(out, {
          key: `zoom-${s.key}-${it.key}-${deco.key}`,
          label: ["Zoom", s.label, it.label, deco.label].filter(Boolean).join(" "),
          category: "Zoom",
          params: {
            scaleFrom: 1 + (s.from - 1) * scale,
            scaleTo:   1 + (s.to   - 1) * scale,
            fade: 1,
            ...deco.extra,
          },
          duration: 0.7,
        });
      }
    }
  }
}

function genBlur(out: TransitionPreset[]) {
  // 5 strengths × 4 colors (incl. none) = 20
  // 5 strengths × 8 directions (blur+slide) = 40 → keep 4 dirs × 5 = 20
  // Total: 40
  const strengths = [
    { key: "1", label: "Light",    blur: 8 },
    { key: "2", label: "Medium",   blur: 16 },
    { key: "3", label: "Heavy",    blur: 28 },
    { key: "4", label: "Extreme",  blur: 44 },
    { key: "5", label: "Cinematic",blur: 64 },
  ];
  const colorTints = [
    { key: "none",  label: "",      extra: {} as ParamTransitionParams },
    { key: "white", label: "White", extra: { color: "#ffffff", colorAmp: 0.4 } as ParamTransitionParams },
    { key: "black", label: "Black", extra: { color: "#000000", colorAmp: 0.5 } as ParamTransitionParams },
    { key: "blue",  label: "Blue",  extra: { color: "#22d3ee", colorAmp: 0.35 } as ParamTransitionParams },
  ];
  for (const s of strengths) {
    for (const c of colorTints) {
      pushPreset(out, {
        key: `blur-${s.key}-${c.key}`,
        label: ["Blur", s.label, c.label].filter(Boolean).join(" "),
        category: "Blur",
        params: { blurPx: s.blur, fade: 1, ...c.extra },
        duration: 0.7,
      });
    }
  }
  // Blur + slide combos
  for (const d of DIR4) {
    for (const s of strengths) {
      pushPreset(out, {
        key: `blur-slide-${d.key}-${s.key}`,
        label: `Blur Slide ${d.arrow} ${s.label}`,
        category: "Blur",
        params: { dx: d.dx * 0.7, dy: d.dy * 0.7, blurPx: s.blur, fade: 1 },
        duration: 0.6,
      });
    }
  }
}

function genSpin(out: TransitionPreset[]) {
  // 4 styles × 4 intensities × 2 decorations = 32
  const styles = [
    { key: "cw",      label: "CW",      deg: 360 },
    { key: "ccw",     label: "CCW",     deg: -360 },
    { key: "half",    label: "Half",    deg: 180 },
    { key: "quad",    label: "Quad",    deg: 720 },
  ];
  const decos = [
    { key: "clean", label: "",     extra: {} as ParamTransitionParams },
    { key: "zoom",  label: "Zoom", extra: { scaleFrom: 0.4, scaleTo: 1.4 } as ParamTransitionParams },
  ];
  for (const s of styles) {
    for (const it of INTENSITY) {
      for (const deco of decos) {
        pushPreset(out, {
          key: `spin-${s.key}-${it.key}-${deco.key}`,
          label: ["Spin", s.label, it.label, deco.label].filter(Boolean).join(" "),
          category: "Spin",
          params: { rotateDeg: s.deg * it.mul, fade: 1, ...deco.extra },
          duration: 0.8,
        });
      }
    }
  }
}

function genIris(out: TransitionPreset[]) {
  // 2 styles × 4 intensities × 6 colors (incl none) = 48
  const styles = [
    { key: "in",  label: "In",  mode: "in"  as const },
    { key: "out", label: "Out", mode: "out" as const },
  ];
  const colors = [
    { key: "none",   label: "",        extra: {} as ParamTransitionParams },
    { key: "white",  label: "White",   extra: { color: "#ffffff", colorAmp: 0.35 } as ParamTransitionParams },
    { key: "black",  label: "Black",   extra: { color: "#000000", colorAmp: 0.5  } as ParamTransitionParams },
    { key: "amber",  label: "Amber",   extra: { color: "#fbbf24", colorAmp: 0.3  } as ParamTransitionParams },
    { key: "rose",   label: "Rose",    extra: { color: "#f43f5e", colorAmp: 0.3  } as ParamTransitionParams },
    { key: "violet", label: "Violet",  extra: { color: "#8b5cf6", colorAmp: 0.3  } as ParamTransitionParams },
  ];
  for (const s of styles) {
    for (const it of INTENSITY) {
      for (const c of colors) {
        pushPreset(out, {
          key: `iris-${s.key}-${it.key}-${c.key}`,
          label: ["Iris", s.label, it.label, c.label].filter(Boolean).join(" "),
          category: "Iris",
          params: { iris: s.mode, scaleFrom: 1 - 0.1 * it.mul, scaleTo: 1 + 0.1 * it.mul, fade: 1, ...c.extra },
          duration: 0.7,
        });
      }
    }
  }
}

function genColorFlash(out: TransitionPreset[]) {
  // 18 colors × 3 styles (flash, fade-to, sustained) = 54
  const styles = [
    { key: "flash",  label: "Flash",  monotonic: false, amp: 0.95 },
    { key: "fade",   label: "Fade To", monotonic: true,  amp: 1.0 },
    { key: "wash",   label: "Wash",   monotonic: false, amp: 0.55 },
  ];
  for (const c of COLOR_PALETTE) {
    for (const s of styles) {
      pushPreset(out, {
        key: `flash-${c.key}-${s.key}`,
        label: `${s.label} ${c.label}`,
        category: "Color Flash",
        params: { color: c.color, colorAmp: s.amp, colorMonotonic: s.monotonic, fade: 1 },
        duration: 0.5,
      });
    }
  }
}

function genDropPop(out: TransitionPreset[]) {
  // 8 directions × 5 styles = 40
  const styles = [
    { key: "drop",      label: "Drop",      mul: 1.0,  rot: 0 },
    { key: "soft",      label: "Soft",      mul: 0.5,  rot: 0 },
    { key: "spring",    label: "Spring",    mul: 1.3,  rot: 0 },
    { key: "tilt",      label: "Tilt",      mul: 1.0,  rot: 18 },
    { key: "tumble",    label: "Tumble",    mul: 1.0,  rot: 90 },
  ];
  for (const d of DIR8) {
    for (const s of styles) {
      pushPreset(out, {
        key: `drop-${d.key}-${s.key}`,
        label: `${s.label} ${d.arrow}`,
        category: "Drop & Pop",
        params: { dx: d.dx * s.mul * 0.4, dy: d.dy * s.mul, rotateDeg: s.rot, fade: 1, scaleFrom: 0.85, scaleTo: 1 },
        duration: 0.55,
      });
    }
  }
}

function genShakeGlitch(out: TransitionPreset[]) {
  // 6 shake intensities × 4 colors = 24, + 12 named glitch combos = 36
  const shakes = [
    { key: "1", label: "Faint",    amp: 4 },
    { key: "2", label: "Light",    amp: 8 },
    { key: "3", label: "Strong",   amp: 14 },
    { key: "4", label: "Extreme",  amp: 22 },
    { key: "5", label: "Earthquake", amp: 32 },
    { key: "6", label: "Rumble",   amp: 18 },
  ];
  const accents = [
    { key: "none",    label: "",       extra: {} as ParamTransitionParams },
    { key: "white",   label: "White",  extra: { color: "#ffffff", colorAmp: 0.4 } as ParamTransitionParams },
    { key: "magenta", label: "Magenta", extra: { color: "#ec4899", colorAmp: 0.45 } as ParamTransitionParams },
    { key: "cyan",    label: "Cyan",   extra: { color: "#22d3ee", colorAmp: 0.45 } as ParamTransitionParams },
  ];
  for (const s of shakes) {
    for (const a of accents) {
      pushPreset(out, {
        key: `shake-${s.key}-${a.key}`,
        label: `Shake ${s.label} ${a.label}`.trim(),
        category: "Shake & Glitch",
        params: { shake: s.amp, fade: 1, ...a.extra },
        duration: 0.4,
      });
    }
  }
  // Named glitch combos
  const glitches = [
    { key: "rgb",       label: "RGB Glitch",     params: { dx: 0.2, color: "#ec4899", colorAmp: 0.4, blurPx: 8 } },
    { key: "vhs",       label: "VHS Tear",       params: { dy: 0.05, color: "#22d3ee", colorAmp: 0.35, shake: 6 } },
    { key: "datamosh",  label: "Datamosh",       params: { blurPx: 24, color: "#a855f7", colorAmp: 0.4 } },
    { key: "static",    label: "Static",         params: { color: "#ffffff", colorAmp: 0.6, shake: 12 } },
    { key: "scan",      label: "Scanline Snap",  params: { wipeTop: 0.5, color: "#22d3ee", colorAmp: 0.3 } },
    { key: "interlace", label: "Interlace",      params: { dy: 0.04, color: "#facc15", colorAmp: 0.25 } },
    { key: "skew",      label: "Skew Glitch",    params: { dx: 0.3, dy: 0.1, blurPx: 6, color: "#ef4444", colorAmp: 0.4 } },
    { key: "drop",      label: "Frame Drop",     params: { color: "#000000", colorAmp: 0.65, fade: 0.5 } },
    { key: "slice",     label: "Slice",          params: { wipeLeft: 0.5, wipeRight: 0.5, color: "#ffffff", colorAmp: 0.3 } },
    { key: "split",     label: "Split RGB",      params: { dx: 0.15, color: "#f43f5e", colorAmp: 0.5, blurPx: 4 } },
    { key: "tear",      label: "Tear",           params: { wipeLeft: 0.4, wipeRight: 0.4, dy: 0.05, color: "#facc15", colorAmp: 0.3 } },
    { key: "burst",     label: "Burst Cut",      params: { scaleFrom: 1.4, color: "#ffffff", colorAmp: 0.7 } },
  ];
  for (const g of glitches) {
    pushPreset(out, {
      key: `glitch-${g.key}`,
      label: g.label,
      category: "Shake & Glitch",
      params: g.params,
      duration: 0.4,
    });
  }
}

function genSwirlMorph(out: TransitionPreset[]) {
  // 8 swirl variants × 5 intensities = 40
  const styles = [
    { key: "swirl",     label: "Swirl",     rot:  120, scaleFrom: 0.6 },
    { key: "swirl-rev", label: "Swirl Rev", rot: -120, scaleFrom: 0.6 },
    { key: "morph",     label: "Morph",     rot:  0,   scaleFrom: 0.85, blur: 10 },
    { key: "warp",      label: "Warp",      rot:  60,  scaleFrom: 0.5,  blur: 18 },
    { key: "twist",     label: "Twist",     rot:  240, scaleFrom: 0.7 },
    { key: "vortex",    label: "Vortex",    rot:  540, scaleFrom: 0.4,  blur: 14 },
    { key: "kaleido",   label: "Kaleido",   rot:  90,  scaleFrom: 0.7,  blur: 6 },
    { key: "fold",      label: "Fold",      rot:  30,  scaleFrom: 0.9,  blur: 8 },
  ];
  for (const s of styles) {
    for (const it of INTENSITY) {
      pushPreset(out, {
        key: `swirl-${s.key}-${it.key}`,
        label: `${s.label} ${it.label}`.trim(),
        category: "Swirl & Morph",
        params: {
          rotateDeg: s.rot * it.mul,
          scaleFrom: 1 - (1 - s.scaleFrom) * it.mul,
          scaleTo:   1 + (1 - s.scaleFrom) * it.mul * 0.5,
          blurPx: (s.blur ?? 0) * it.mul,
          fade: 1,
        },
        duration: 0.8,
      });
    }
  }
}

function genCinematic(out: TransitionPreset[]) {
  // 60 hand-tuned named entries giving the picker some "Hollywood" flavor.
  const cines: { key: string; label: string; params: ParamTransitionParams }[] = [
    { key: "filmburn",       label: "Film Burn",        params: { color: "#fb923c", colorAmp: 0.85, blurPx: 6, fade: 1 } },
    { key: "lightleak-warm", label: "Warm Light Leak",  params: { color: "#fbbf24", colorAmp: 0.6, fade: 0.9 } },
    { key: "lightleak-cool", label: "Cool Light Leak",  params: { color: "#22d3ee", colorAmp: 0.6, fade: 0.9 } },
    { key: "lightleak-rose", label: "Rose Light Leak",  params: { color: "#f9a8d4", colorAmp: 0.6, fade: 0.9 } },
    { key: "fade-cinema",    label: "Cinema Fade",      params: { color: "#000000", colorAmp: 0.9, colorMonotonic: true } },
    { key: "fade-soft",      label: "Soft Fade",        params: { fade: 0.5 } },
    { key: "fade-to-white",  label: "Fade to White",    params: { color: "#ffffff", colorAmp: 1, colorMonotonic: true } },
    { key: "dream",          label: "Dream",            params: { blurPx: 22, color: "#ffffff", colorAmp: 0.4, scaleFrom: 0.9, fade: 1 } },
    { key: "memory",         label: "Memory",           params: { blurPx: 12, color: "#fef3c7", colorAmp: 0.5, fade: 0.95 } },
    { key: "flashback",      label: "Flashback",        params: { blurPx: 30, color: "#fde68a", colorAmp: 0.55, scaleFrom: 1.2, fade: 1 } },
    { key: "noir",           label: "Noir",             params: { color: "#0c0a09", colorAmp: 0.7, blurPx: 6, fade: 0.9 } },
    { key: "sepia",          label: "Sepia",            params: { color: "#a16207", colorAmp: 0.6, fade: 0.9 } },
    { key: "vhs-fade",       label: "VHS Fade",         params: { dx: 0.1, color: "#22d3ee", colorAmp: 0.4, blurPx: 4 } },
    { key: "tv-off",         label: "TV Off",           params: { wipeTop: 0.45, wipeBottom: 0.45, color: "#000000", colorAmp: 0.7 } },
    { key: "tv-on",          label: "TV On",            params: { wipeLeft: 0.45, wipeRight: 0.45, color: "#ffffff", colorAmp: 0.5 } },
    { key: "shutter-h",      label: "Shutter ↔",        params: { wipeLeft: 0.5, wipeRight: 0.5, fade: 1 } },
    { key: "shutter-v",      label: "Shutter ↕",        params: { wipeTop: 0.5, wipeBottom: 0.5, fade: 1 } },
    { key: "barn-h",         label: "Barn Door H",      params: { wipeLeft: 0.5, wipeRight: 0.5 } },
    { key: "barn-v",         label: "Barn Door V",      params: { wipeTop: 0.5, wipeBottom: 0.5 } },
    { key: "ripple-soft",    label: "Ripple Soft",      params: { scaleFrom: 0.95, scaleTo: 1.05, blurPx: 6, fade: 1 } },
    { key: "morph-soft",     label: "Morph Soft",       params: { scaleFrom: 0.92, scaleTo: 1.08, blurPx: 10, fade: 1 } },
    { key: "popup",          label: "Pop Up",           params: { dy: -1, scaleFrom: 0.6, fade: 1 } },
    { key: "popdown",        label: "Pop Down",         params: { dy:  1, scaleFrom: 0.6, fade: 1 } },
    { key: "swing-in",       label: "Swing In",         params: { rotateDeg: -25, dy: -0.15, fade: 1 } },
    { key: "swing-out",      label: "Swing Out",        params: { rotateDeg:  25, dy:  0.15, fade: 1 } },
    { key: "elastic-in",     label: "Elastic In",       params: { scaleFrom: 0.7, scaleTo: 1.1, fade: 1 } },
    { key: "elastic-out",    label: "Elastic Out",      params: { scaleFrom: 1.2, scaleTo: 0.95, fade: 1 } },
    { key: "iris-cinema",    label: "Iris Cinema",      params: { iris: "in", color: "#000000", colorAmp: 0.5 } },
    { key: "iris-vintage",   label: "Iris Vintage",     params: { iris: "out", color: "#7c2d12", colorAmp: 0.5 } },
    { key: "checker",        label: "Checker",          params: { fade: 0.6, blurPx: 4 } },
    { key: "pixel",          label: "Pixel Dissolve",   params: { fade: 0.5, blurPx: 8 } },
    { key: "burn-blue",      label: "Blue Burn",        params: { color: "#3b82f6", colorAmp: 0.8, blurPx: 6 } },
    { key: "burn-violet",    label: "Violet Burn",      params: { color: "#8b5cf6", colorAmp: 0.8, blurPx: 6 } },
    { key: "burn-emerald",   label: "Emerald Burn",     params: { color: "#10b981", colorAmp: 0.8, blurPx: 6 } },
    { key: "smear",          label: "Smear",            params: { dx: 0.6, blurPx: 24, fade: 1 } },
    { key: "smear-up",       label: "Smear Up",         params: { dy: 0.6, blurPx: 24, fade: 1 } },
    { key: "drop-zoom",      label: "Drop + Zoom",      params: { dy: -0.6, scaleFrom: 0.6, fade: 1 } },
    { key: "rise-zoom",      label: "Rise + Zoom",      params: { dy: 0.6, scaleFrom: 0.6, fade: 1 } },
    { key: "burst",          label: "Burst",            params: { scaleFrom: 1.5, color: "#ffffff", colorAmp: 0.6 } },
    { key: "implode",        label: "Implode",          params: { scaleFrom: 1.4, scaleTo: 0.6, blurPx: 10 } },
    { key: "explode",        label: "Explode",          params: { scaleFrom: 0.6, scaleTo: 1.5, blurPx: 14, color: "#ffffff", colorAmp: 0.4 } },
    { key: "pageflip-l",     label: "Page Flip ←",      params: { dx: 1, rotateDeg: 30, scaleFrom: 0.8 } },
    { key: "pageflip-r",     label: "Page Flip →",      params: { dx: -1, rotateDeg: -30, scaleFrom: 0.8 } },
    { key: "pageflip-u",     label: "Page Flip ↑",      params: { dy: 1, rotateDeg: 25, scaleFrom: 0.8 } },
    { key: "pageflip-d",     label: "Page Flip ↓",      params: { dy: -1, rotateDeg: -25, scaleFrom: 0.8 } },
    { key: "cube-l",         label: "Cube ←",           params: { dx: 1, rotateDeg: 90 } },
    { key: "cube-r",         label: "Cube →",           params: { dx: -1, rotateDeg: -90 } },
    { key: "cube-u",         label: "Cube ↑",           params: { dy: 1, rotateDeg: 90 } },
    { key: "cube-d",         label: "Cube ↓",           params: { dy: -1, rotateDeg: -90 } },
    { key: "rolloff",        label: "Roll Off",         params: { dx: 1, rotateDeg: 360, scaleFrom: 0.7 } },
    { key: "rollon",         label: "Roll On",          params: { dx: -1, rotateDeg: -360, scaleFrom: 0.7 } },
    { key: "fall",           label: "Fall Down",        params: { dy: -1, rotateDeg: 35, scaleFrom: 0.85 } },
    { key: "lift",           label: "Lift Up",          params: { dy: 1, rotateDeg: -10, scaleFrom: 0.95 } },
    { key: "vortex-fade",    label: "Vortex Fade",      params: { rotateDeg: 540, scaleFrom: 0.3, blurPx: 18, fade: 1 } },
    { key: "twirl",          label: "Twirl",            params: { rotateDeg: 720, scaleFrom: 0.6, fade: 1 } },
    { key: "crash",          label: "Crash Cut",        params: { shake: 24, color: "#ffffff", colorAmp: 0.7 } },
    { key: "boom",           label: "Boom",             params: { scaleFrom: 1.6, color: "#fbbf24", colorAmp: 0.6, blurPx: 12 } },
    { key: "snap",           label: "Snap",             params: { scaleFrom: 0.85, color: "#ffffff", colorAmp: 0.5 } },
    { key: "ghost",          label: "Ghost",            params: { fade: 0.4, blurPx: 16, color: "#ffffff", colorAmp: 0.3 } },
    { key: "ethereal",       label: "Ethereal",         params: { fade: 0.5, blurPx: 20, color: "#a5f3fc", colorAmp: 0.4 } },
    { key: "neonbloom",      label: "Neon Bloom",       params: { color: "#ec4899", colorAmp: 0.5, blurPx: 14, scaleFrom: 0.9 } },
  ];
  for (const c of cines) {
    pushPreset(out, {
      key: `cine-${c.key}`,
      label: c.label,
      category: "Cinematic",
      params: c.params,
      duration: 0.7,
    });
  }
}

function genReveal(out: TransitionPreset[]) {
  // 8 directions × 4 intensities × 2 styles (clean / colored edge) = 64
  const styles = [
    { key: "clean", label: "",      extra: {} as ParamTransitionParams },
    { key: "tint",  label: "Tint",  extra: { color: "#ffffff", colorAmp: 0.3 } as ParamTransitionParams },
  ];
  for (const d of DIR8) {
    for (const it of INTENSITY) {
      for (const s of styles) {
        pushPreset(out, {
          key: `reveal-${d.key}-${it.key}-${s.key}`,
          label: `Reveal ${d.arrow} ${it.label} ${s.label}`.replace(/\s+/g, " ").trim(),
          category: "Reveal",
          params: {
            wipeLeft:   d.dx > 0 ? 0.5 * it.mul : 0,
            wipeRight:  d.dx < 0 ? 0.5 * it.mul : 0,
            wipeTop:    d.dy > 0 ? 0.5 * it.mul : 0,
            wipeBottom: d.dy < 0 ? 0.5 * it.mul : 0,
            scaleFrom: 0.95,
            ...s.extra,
          },
          duration: 0.6,
        });
      }
    }
  }
}

// ── Catalog assembly ───────────────────────────────────────────────────────

function buildAllPresets(): TransitionPreset[] {
  const out: TransitionPreset[] = [];
  genSlide(out);        // 64
  genPush(out);         // 64
  genWipe(out);         // 48
  genZoom(out);         // 48
  genBlur(out);         // 40
  genSpin(out);         // 32
  genIris(out);         // 48
  genColorFlash(out);   // 54
  genDropPop(out);      // 40
  genShakeGlitch(out);  // 36
  genSwirlMorph(out);   // 40
  genCinematic(out);    // 60
  genReveal(out);       // 64
  // Subtotal: 638 — well over 500. Keep them all so the user has variety.
  return out;
}

export const TRANSITION_PRESETS: TransitionPreset[] = buildAllPresets();

export const TRANSITION_PRESET_CATEGORIES: TransitionPresetCategory[] = [
  "Slide", "Push", "Wipe", "Zoom", "Blur", "Spin", "Iris",
  "Color Flash", "Drop & Pop", "Shake & Glitch", "Swirl & Morph",
  "Cinematic", "Reveal",
];

export function getTransitionPreset(key: string): TransitionPreset | undefined {
  return TRANSITION_PRESETS.find((p) => p.key === key);
}
